-- luacheck: std min+busted
local helpers = require("authentik/authentik_helpers")

describe("authentik helpers", function()
	describe("starts_with", function()
		it("matches a prefix", function()
			assert.is_true(helpers.starts_with("x-authentik-username", "x-authentik-"))
		end)
		it("rejects a non-match", function()
			assert.is_false(helpers.starts_with("authorization", "x-authentik-"))
		end)
		it("is safe on nil / empty inputs", function()
			assert.is_false(helpers.starts_with(nil, "x-"))
			assert.is_false(helpers.starts_with("x", ""))
			assert.is_false(helpers.starts_with("x", nil))
		end)
	end)

	describe("rstrip_slash", function()
		it("strips a single trailing slash", function()
			assert.equals("/outpost", helpers.rstrip_slash("/outpost/"))
		end)
		it("strips repeated trailing slashes", function()
			assert.equals("/a", helpers.rstrip_slash("/a///"))
		end)
		it("leaves a slash-free string untouched", function()
			assert.equals("http://x:9000", helpers.rstrip_slash("http://x:9000"))
		end)
		it("passes nil / empty through", function()
			assert.is_nil(helpers.rstrip_slash(nil))
			assert.equals("", helpers.rstrip_slash(""))
		end)
	end)

	describe("split_headers", function()
		it("splits on spaces and commas", function()
			assert.same({ "X-A", "X-B", "X-C" }, helpers.split_headers("X-A, X-B  X-C"))
		end)
		it("returns an empty table for nil", function()
			assert.same({}, helpers.split_headers(nil))
		end)
		it("handles a single header", function()
			assert.same({ "X-Only" }, helpers.split_headers("X-Only"))
		end)
	end)
end)
