-- luacheck: std min+busted
local helpers = require("discord/discord_helpers")

describe("discord helpers", function()
	describe("format_field", function()
		it("leaves a short string untouched", function()
			assert.equals("hello", helpers.format_field("hello"))
		end)
		it("leaves a string of exactly 1021 chars untouched", function()
			local s = string.rep("a", 1021)
			assert.equals(s, helpers.format_field(s))
		end)
		it("truncates a 1022-char string to 1021 chars plus an ellipsis", function()
			local s = string.rep("a", 1022)
			local out = helpers.format_field(s)
			assert.equals(1024, #out)
			assert.equals(string.rep("a", 1021) .. "...", out)
		end)
		it("truncates a very long string to 1024 chars total", function()
			local out = helpers.format_field(string.rep("b", 5000))
			assert.equals(1024, #out)
			assert.equals(string.rep("b", 1021) .. "...", out)
		end)
	end)
end)
