-- luacheck: std min+busted
local helpers = require("matrix/matrix_helpers")

describe("matrix helpers", function()
	describe("html_escape", function()
		it("escapes the three markup-significant characters", function()
			assert.equals("&amp;&lt;&gt;", helpers.html_escape("&<>"))
		end)
		it("escapes inside a larger string", function()
			assert.equals("a &lt;b&gt; &amp; c", helpers.html_escape("a <b> & c"))
		end)
		it("leaves a plain string untouched", function()
			assert.equals("plain text 1.2.3.4", helpers.html_escape("plain text 1.2.3.4"))
		end)
		it("coerces non-string input via tostring", function()
			assert.equals("123", helpers.html_escape(123))
		end)
	end)

	describe("escape_pattern", function()
		it("escapes every Lua pattern magic character", function()
			assert.equals("%(%)%.%%%+%-%*%?%[%]%^%$", helpers.escape_pattern("().%+-*?[]^$"))
		end)
		it("leaves a magic-free string untouched", function()
			assert.equals("abc123", helpers.escape_pattern("abc123"))
		end)
		it("produces a string usable as a literal gsub pattern", function()
			local ip = "1.2.3.4"
			local escaped = helpers.escape_pattern(ip)
			-- With escaping the dots match literally, so only the exact IP is replaced.
			assert.equals("X and 1a2a3a4", (string.gsub("1.2.3.4 and 1a2a3a4", escaped, "X")))
		end)
	end)

	describe("anonymize_ip", function()
		it("masks the last two octets of an IPv4 address", function()
			assert.equals("1.2.xxx.xxx", helpers.anonymize_ip("1.2.3.4"))
		end)
		it("masks all but the first three hextets of an IPv6 address", function()
			assert.equals("2001:db8:1:xxxx", helpers.anonymize_ip("2001:db8:1:2::5"))
		end)
		it("masks an IPv4-mapped IPv6 address via the IPv6 branch", function()
			assert.equals("::ffff:xxxx", helpers.anonymize_ip("::ffff:1.2.3.4"))
		end)
		it("falls back to a generic mask for a degenerate IPv6 address", function()
			assert.equals("xxxx::xxxx", helpers.anonymize_ip("::1"))
		end)
	end)
end)
