-- luacheck: std min+busted
local helpers = require("matrix/matrix_helpers")

describe("matrix helpers", function()
	describe("html_escape", function()
		it("escapes the three markup-significant characters", function()
			assert.equals("&amp;&lt;&gt;", helpers.html_escape("&<>"))
		end)
		it("escapes inside a larger string", function()
			assert.equals("a &lt;b&gt; &amp; c", helpers.html_escape("a <b> & c"))
		end)
		it("leaves a plain string untouched", function()
			assert.equals("plain text 1.2.3.4", helpers.html_escape("plain text 1.2.3.4"))
		end)
		it("coerces non-string input via tostring", function()
			assert.equals("123", helpers.html_escape(123))
		end)
	end)

	describe("escape_pattern", function()
		it("escapes every Lua pattern magic character", function()
			assert.equals("%(%)%.%%%+%-%*%?%[%]%^%$", helpers.escape_pattern("().%+-*?[]^$"))
		end)
		it("leaves a magic-free string untouched", function()
			assert.equals("abc123", helpers.escape_pattern("abc123"))
		end)
		it("produces a string usable as a literal gsub pattern", function()
			local ip = "1.2.3.4"
			local escaped = helpers.escape_pattern(ip)
			-- With escaping the dots match literally, so only the exact IP is replaced.
			assert.equals("X and 1a2a3a4", (string.gsub("1.2.3.4 and 1a2a3a4", escaped, "X")))
		end)
	end)

	describe("anonymize_ip", function()
		it("masks the last two octets of an IPv4 address", function()
			assert.equals("1.2.xxx.xxx", helpers.anonymize_ip("1.2.3.4"))
		end)
		it("masks all but the first three hextets of an IPv6 address", function()
			assert.equals("2001:db8:1:xxxx", helpers.anonymize_ip("2001:db8:1:2::5"))
		end)
		it("masks an IPv4-mapped IPv6 address via the IPv6 branch", function()
			assert.equals("::ffff:xxxx", helpers.anonymize_ip("::ffff:1.2.3.4"))
		end)
		it("falls back to a generic mask for a degenerate IPv6 address", function()
			assert.equals("xxxx::xxxx", helpers.anonymize_ip("::1"))
		end)
	end)

	describe("flatten_header_value", function()
		it("returns a plain string unchanged", function()
			assert.equals("text/html", helpers.flatten_header_value("text/html"))
		end)
		it("joins a repeated-header table with a comma", function()
			assert.equals("a, b, c", helpers.flatten_header_value({ "a", "b", "c" }))
		end)
		it("coerces a non-string scalar via tostring", function()
			assert.equals("123", helpers.flatten_header_value(123))
		end)
	end)

	describe("redact_header", function()
		it("redacts the value of sensitive headers", function()
			assert.equals("[REDACTED]", helpers.redact_header("authorization", "Bearer secret"))
			assert.equals("[REDACTED]", helpers.redact_header("cookie", "session=abc"))
			assert.equals("[REDACTED]", helpers.redact_header("set-cookie", "session=abc"))
			assert.equals("[REDACTED]", helpers.redact_header("x-api-key", "k"))
			assert.equals("[REDACTED]", helpers.redact_header("x-csrf-token", "t"))
			assert.equals("[REDACTED]", helpers.redact_header("x-xsrf-token", "t"))
			assert.equals("[REDACTED]", helpers.redact_header("proxy-authorization", "Basic x"))
		end)
		it("matches sensitive header names case-insensitively", function()
			assert.equals("[REDACTED]", helpers.redact_header("Authorization", "Bearer secret"))
			assert.equals("[REDACTED]", helpers.redact_header("COOKIE", "session=abc"))
		end)
		it("redacts even when a sensitive header is repeated (table value)", function()
			assert.equals("[REDACTED]", helpers.redact_header("cookie", { "a=1", "b=2" }))
		end)
		it("passes non-sensitive headers through, flattening tables", function()
			assert.equals("example.com", helpers.redact_header("host", "example.com"))
			assert.equals("gzip, br", helpers.redact_header("accept-encoding", { "gzip", "br" }))
		end)
	end)
end)
