-- luacheck: std min+busted
local helpers = require("openappsec/openappsec_helpers")

describe("openappsec helpers", function()
	describe("verdict", function()
		it("accepts a 200 response with a lowercase marker", function()
			local verdict, reason = helpers.verdict({ status = 200, headers = { ["x-openappsec-judge"] = "pass" } })
			assert.equals("accept", verdict)
			assert.equals("status 200", reason)
		end)

		it("accepts a 200 response with a title-case marker", function()
			local verdict, reason = helpers.verdict({ status = 200, headers = { ["X-Openappsec-Judge"] = "pass" } })
			assert.equals("accept", verdict)
			assert.equals("status 200", reason)
		end)

		it("denies a 403 response", function()
			local verdict, reason = helpers.verdict({ status = 403, headers = {} })
			assert.equals("deny", verdict)
			assert.equals("status 403", reason)
		end)

		it("denies a 200 response without the marker", function()
			local verdict, reason = helpers.verdict({ status = 200, headers = {} })
			assert.equals("deny", verdict)
			assert.equals("status 200 without judge marker", reason)
		end)

		it("denies a redirect", function()
			local verdict, reason = helpers.verdict({ status = 307, headers = { ["x-openappsec-judge"] = "pass" } })
			assert.equals("deny", verdict)
			assert.equals("status 307", reason)
		end)

		it("treats a judge 5xx as an error, not a verdict", function()
			for _, status in ipairs({ 500, 502, 504 }) do
				local verdict, reason = helpers.verdict({ status = status, headers = {} })
				assert.equals("error", verdict)
				assert.equals("judge returned status " .. status, reason)
			end
		end)

		it("accepts a duplicated marker header (table value) by its first entry", function()
			local verdict = helpers.verdict({ status = 200, headers = { ["x-openappsec-judge"] = { "pass", "pass" } } })
			assert.equals("accept", verdict)
		end)

		it("denies a 200 without any headers table", function()
			local verdict = helpers.verdict({ status = 200 })
			assert.equals("deny", verdict)
		end)

		it("denies a 200 whose marker is not pass", function()
			local verdict = helpers.verdict({ status = 200, headers = { ["x-openappsec-judge"] = "fail" } })
			assert.equals("deny", verdict)
		end)

		it("returns an error and propagates the error string for no response", function()
			local verdict, reason = helpers.verdict(nil, "connection refused")
			assert.equals("error", verdict)
			assert.equals("connection refused", reason)
		end)
	end)

	describe("event_id", function()
		it("reads the judge's X-Event-ID header in either casing", function()
			assert.equals("abc-1", helpers.event_id({ status = 403, headers = { ["x-event-id"] = "abc-1" } }))
			assert.equals("abc-2", helpers.event_id({ status = 403, headers = { ["X-Event-ID"] = "abc-2" } }))
		end)
		it("takes the first value of a duplicated header", function()
			assert.equals(
				"abc-3",
				helpers.event_id({ status = 403, headers = { ["x-event-id"] = { "abc-3", "abc-4" } } })
			)
		end)
		it("is nil without a response, without headers, or with an empty header", function()
			assert.is_nil(helpers.event_id(nil))
			assert.is_nil(helpers.event_id({ status = 200 }))
			assert.is_nil(helpers.event_id({ status = 403, headers = { ["x-event-id"] = "" } }))
		end)
	end)

	describe("parse_list", function()
		it("splits on spaces and commas and applies the transform", function()
			assert.same({ "OPTIONS", "HEAD" }, helpers.parse_list("options, head", string.upper))
			assert.same({ "^/healthz$", "^/webhooks/" }, helpers.parse_list(" ^/healthz$  ^/webhooks/ "))
			assert.same({}, helpers.parse_list(nil))
			assert.same({}, helpers.parse_list(""))
		end)
	end)

	describe("is_excluded", function()
		local function plain_find(subject, pattern)
			return subject:find(pattern) ~= nil
		end
		it("excludes listed methods regardless of case", function()
			local excluded, why = helpers.is_excluded("/", "options", {}, { "OPTIONS" }, plain_find)
			assert.is_true(excluded)
			assert.equals("method OPTIONS", why)
		end)
		it("excludes a path matched by one of the patterns", function()
			local excluded, why = helpers.is_excluded("/healthz", "GET", { "^/nope", "^/healthz$" }, {}, plain_find)
			assert.is_true(excluded)
			assert.equals("uri matches ^/healthz$", why)
		end)
		it("keeps everything else", function()
			assert.is_false(helpers.is_excluded("/healthz-not", "GET", { "^/healthz$" }, { "OPTIONS" }, plain_find))
			assert.is_false(helpers.is_excluded("/", "GET", {}, {}, plain_find))
		end)
	end)

	describe("strip_headers", function()
		it("removes the named headers case-insensitively and keeps the rest", function()
			local headers = { ["Authorization"] = "x", ["cookie"] = "y", ["User-Agent"] = "ua" }
			helpers.strip_headers(headers, { "authorization", "Cookie" })
			assert.same({ ["User-Agent"] = "ua" }, headers)
		end)
	end)

	describe("body_policy", function()
		it("replays by default", function()
			assert.is_true(helpers.body_policy(1024, true, 0))
			assert.is_true(helpers.body_policy(nil, true, 100))
		end)
		it("skips when inspection is off", function()
			local ok, why = helpers.body_policy(10, false, 0)
			assert.is_false(ok)
			assert.equals("OPENAPPSEC_INSPECT_BODY is no", why)
		end)
		it("skips a body above the limit and names both sizes", function()
			local ok, why = helpers.body_policy(2048, true, 1024)
			assert.is_false(ok)
			assert.equals("body of 2048 bytes exceeds OPENAPPSEC_MAX_BODY_SIZE (1024)", why)
			assert.is_true(helpers.body_policy(1024, true, 1024))
		end)
	end)

	describe("in_cooldown", function()
		it("is active only before the deadline", function()
			assert.is_true(helpers.in_cooldown(100, 99))
			assert.is_false(helpers.in_cooldown(100, 100))
			assert.is_false(helpers.in_cooldown(nil, 5))
		end)
	end)

	describe("canary_state", function()
		it("reports a missing response as down", function()
			local state, reason = helpers.canary_state(nil, "connection refused")
			assert.equals("down", state)
			assert.equals("connection refused", reason)
		end)

		it("reports a denied canary as enforcing", function()
			local state, reason = helpers.canary_state({ status = 403, headers = {} })
			assert.equals("enforcing", state)
			assert.equals("status 403", reason)
		end)

		it("reports an accepted canary as not enforcing", function()
			local state, reason = helpers.canary_state({ status = 200, headers = { ["x-openappsec-judge"] = "pass" } })
			assert.equals("not_enforcing", state)
			assert.equals("status 200", reason)
		end)

		it("reports a judge error as down", function()
			local state, reason = helpers.canary_state({ status = 503, headers = {} })
			assert.equals("down", state)
			assert.equals("judge returned status 503", reason)
		end)
	end)

	describe("canary_ttl", function()
		it("keeps short probe intervals at least 30 seconds", function()
			assert.equals(30, helpers.canary_ttl(10))
		end)

		it("tracks longer probe intervals", function()
			assert.equals(180, helpers.canary_ttl(60))
		end)
	end)
end)
