-- luacheck: std min+busted
local fake = require("spec/helpers/fake_ipmatcher")
local helpers = require("syswarden/syswarden_helpers")

local function matchers(t)
	return {
		blocklist = t.blocklist and fake.new(t.blocklist) or nil,
		whitelist = t.whitelist and fake.new(t.whitelist) or nil,
	}
end

describe("syswarden helpers", function()
	describe("request_enabled", function()
		it("requires the master switch as well as a per-service list", function()
			assert.is_true(helpers.request_enabled("yes", "yes", "no"))
			assert.is_true(helpers.request_enabled("yes", "no", "yes"))
			assert.is_false(helpers.request_enabled("no", "yes", "yes"))
			assert.is_false(helpers.request_enabled("yes", "no", "no"))
		end)
	end)

	describe("matchers_empty", function()
		it("is true until one compiled matcher exists", function()
			assert.is_true(helpers.matchers_empty(nil))
			assert.is_true(helpers.matchers_empty({}))
			assert.is_false(helpers.matchers_empty(matchers({ blocklist = { "1.2.3.4" } })))
			assert.is_false(helpers.matchers_empty(matchers({ whitelist = { "9.9.9.9" } })))
		end)
	end)

	describe("match_any", function()
		it("matches through an already-compiled matcher", function()
			assert.is_true(helpers.match_any(fake.new({ "1.2.3.4" }), "1.2.3.4"))
			assert.is_false(helpers.match_any(fake.new({ "1.2.3.4" }), "8.8.8.8"))
		end)
		it("treats a missing matcher as empty", function()
			assert.is_false(helpers.match_any(nil, "8.8.8.8"))
		end)
		it("propagates construction and match errors", function()
			local matched, err = helpers.match_any(nil, "1.2.3.4", "construction boom")
			assert.is_nil(matched)
			assert.equals("construction boom", err)
			matched, err = helpers.match_any(fake.new_match_err({ "1.2.3.4" }), "1.2.3.4")
			assert.is_nil(matched)
			assert.equals("match boom", err)
		end)
	end)

	describe("decide", function()
		it("blocks an address on the blocklist", function()
			assert.equals("blocked", helpers.decide(matchers({ blocklist = { "1.2.3.4" } }), {}, "1.2.3.4"))
		end)
		it("allows an unknown address", function()
			assert.equals("no-match", helpers.decide(matchers({ blocklist = { "1.2.3.4" } }), {}, "8.8.8.8"))
		end)
		it("lets the whitelist win over the blocklist", function()
			local both = matchers({ blocklist = { "1.2.3.4" }, whitelist = { "1.2.3.4" } })
			assert.equals("whitelisted", helpers.decide(both, {}, "1.2.3.4"))
		end)
		it("returns no-match when neither matcher exists", function()
			assert.equals("no-match", helpers.decide({}, {}, "1.2.3.4"))
		end)
		it("propagates either matcher construction error", function()
			local verdict, err = helpers.decide({}, { whitelist = "whitelist boom" }, "1.2.3.4")
			assert.is_nil(verdict)
			assert.equals("whitelist boom", err)
			verdict, err =
				helpers.decide(matchers({ whitelist = { "9.9.9.9" } }), { blocklist = "blocklist boom" }, "1.2.3.4")
			assert.is_nil(verdict)
			assert.equals("blocklist boom", err)
		end)
	end)

	describe("list_sizes", function()
		it("counts both lists, absent ones as zero", function()
			assert.same({ 2, 1 }, { helpers.list_sizes({ blocklist = { "a", "b" }, whitelist = { "c" } }) })
			assert.same({ 0, 0 }, { helpers.list_sizes(nil) })
		end)
	end)
end)
