-- luacheck: std min+busted
local fake = require("spec/helpers/fake_ipmatcher")
local helpers = require("syswarden/syswarden_helpers")

local function lists(t)
	return { blocklist = t.blocklist or {}, whitelist = t.whitelist or {} }
end

describe("syswarden helpers", function()
	describe("cache_key", function()
		it("separates server_name and element so they can't collide", function()
			assert.equals("plugin_syswarden_example.com_1.2.3.4", helpers.cache_key("example.com", "1.2.3.4"))
			assert.are_not.equals(
				helpers.cache_key("example.com", "1.2.3.4"),
				helpers.cache_key("example.com1", ".2.3.4")
			)
		end)
	end)

	describe("classify_cache", function()
		it("maps a miss (nil) to 'miss'", function()
			assert.equals("miss", helpers.classify_cache(nil))
		end)
		it("maps a cached 'blocked' to 'deny'", function()
			-- A boolean cache would turn this into an allow and silently disable the
			-- blocklist; that is why the verdict stays a string end to end.
			assert.equals("deny", helpers.classify_cache("blocked"))
		end)
		it("maps every other cached verdict to 'allow'", function()
			assert.equals("allow", helpers.classify_cache("whitelisted"))
			assert.equals("allow", helpers.classify_cache("no-match"))
		end)
	end)

	describe("lists_empty", function()
		it("is true for nil / all-empty lists", function()
			assert.is_true(helpers.lists_empty(nil))
			assert.is_true(helpers.lists_empty({}))
			assert.is_true(helpers.lists_empty(lists({})))
		end)
		it("is false as soon as one list has an entry", function()
			assert.is_false(helpers.lists_empty(lists({ blocklist = { "1.2.3.4" } })))
			assert.is_false(helpers.lists_empty(lists({ whitelist = { "9.9.9.9" } })))
		end)
	end)

	describe("match_any", function()
		it("matches an address in the list", function()
			assert.is_true(helpers.match_any({ "1.2.3.4" }, "1.2.3.4", fake.new))
		end)
		it("returns false when nothing matches", function()
			assert.is_false(helpers.match_any({ "1.2.3.4" }, "8.8.8.8", fake.new))
		end)
		it("treats a nil list as empty", function()
			assert.is_false(helpers.match_any(nil, "8.8.8.8", fake.new))
		end)
		it("propagates a matcher construction error", function()
			local matched, err = helpers.match_any({}, "1.2.3.4", fake.new_err)
			assert.is_nil(matched)
			assert.equals("construction boom", err)
		end)
		it("propagates a matcher :match error", function()
			local matched, err = helpers.match_any({ "1.2.3.4" }, "1.2.3.4", fake.new_match_err)
			assert.is_nil(matched)
			assert.equals("match boom", err)
		end)
	end)

	describe("decide", function()
		it("blocks an address on the blocklist", function()
			assert.equals("blocked", helpers.decide(lists({ blocklist = { "1.2.3.4" } }), "1.2.3.4", fake.new))
		end)
		it("allows an unknown address", function()
			assert.equals("no-match", helpers.decide(lists({ blocklist = { "1.2.3.4" } }), "8.8.8.8", fake.new))
		end)
		it("lets the whitelist win over the blocklist", function()
			-- The operator's explicit allow beats a blocklist entry, so a monitoring
			-- probe caught by a feed keeps working.
			local both = lists({ blocklist = { "1.2.3.4" }, whitelist = { "1.2.3.4" } })
			assert.equals("whitelisted", helpers.decide(both, "1.2.3.4", fake.new))
		end)
		it("returns no-match on empty lists (caller fails open)", function()
			assert.equals("no-match", helpers.decide(lists({}), "1.2.3.4", fake.new))
			assert.equals("no-match", helpers.decide(nil, "1.2.3.4", fake.new))
		end)
		it("propagates a matcher error instead of denying", function()
			local verdict, err = helpers.decide(lists({ blocklist = { "1.2.3.4" } }), "1.2.3.4", fake.new_err)
			assert.is_nil(verdict)
			assert.equals("construction boom", err)
		end)
	end)

	describe("list_sizes", function()
		it("counts both lists, absent ones as zero", function()
			assert.same({ 2, 1 }, { helpers.list_sizes(lists({ blocklist = { "a", "b" }, whitelist = { "c" } })) })
			assert.same({ 0, 0 }, { helpers.list_sizes(nil) })
			assert.same({ 0, 0 }, { helpers.list_sizes({}) })
		end)
	end)
end)
