-- luacheck: std min+busted
local helpers = require("virustotal/virustotal_helpers")

describe("virustotal helpers", function()
	describe("evaluate", function()
		it("returns clean when both counts are within thresholds", function()
			assert.equals("clean", helpers.evaluate(0, 0, 0, 0))
			assert.equals("clean", helpers.evaluate(3, 1, 5, 2))
		end)
		it("treats a count equal to its threshold as clean (strict >)", function()
			assert.equals("clean", helpers.evaluate(5, 2, 5, 2))
		end)
		it("flags when suspicious exceeds its threshold", function()
			assert.equals("6 suspicious and 0 malicious", helpers.evaluate(6, 0, 5, 2))
		end)
		it("flags when malicious exceeds its threshold", function()
			assert.equals("0 suspicious and 3 malicious", helpers.evaluate(0, 3, 5, 2))
		end)
		it("flags when both exceed", function()
			assert.equals("10 suspicious and 4 malicious", helpers.evaluate(10, 4, 5, 2))
		end)
	end)
end)
