-- luacheck: std min+busted
local helpers = require("webhook/webhook_helpers")

describe("webhook helpers", function()
	describe("flatten_header_value", function()
		it("returns a plain string unchanged", function()
			assert.equals("text/html", helpers.flatten_header_value("text/html"))
		end)
		it("joins a repeated-header table with a comma", function()
			assert.equals("a, b, c", helpers.flatten_header_value({ "a", "b", "c" }))
		end)
		it("coerces a non-string scalar via tostring", function()
			assert.equals("123", helpers.flatten_header_value(123))
		end)
	end)

	describe("redact_header", function()
		it("redacts the value of sensitive headers", function()
			assert.equals("[REDACTED]", helpers.redact_header("authorization", "Bearer secret"))
			assert.equals("[REDACTED]", helpers.redact_header("cookie", "session=abc"))
			assert.equals("[REDACTED]", helpers.redact_header("set-cookie", "session=abc"))
			assert.equals("[REDACTED]", helpers.redact_header("x-api-key", "k"))
			assert.equals("[REDACTED]", helpers.redact_header("x-csrf-token", "t"))
			assert.equals("[REDACTED]", helpers.redact_header("x-xsrf-token", "t"))
			assert.equals("[REDACTED]", helpers.redact_header("proxy-authorization", "Basic x"))
		end)
		it("matches sensitive header names case-insensitively", function()
			assert.equals("[REDACTED]", helpers.redact_header("Authorization", "Bearer secret"))
			assert.equals("[REDACTED]", helpers.redact_header("COOKIE", "session=abc"))
		end)
		it("redacts even when a sensitive header is repeated (table value)", function()
			assert.equals("[REDACTED]", helpers.redact_header("cookie", { "a=1", "b=2" }))
		end)
		it("passes non-sensitive headers through, flattening tables", function()
			assert.equals("example.com", helpers.redact_header("host", "example.com"))
			assert.equals("gzip, br", helpers.redact_header("accept-encoding", { "gzip", "br" }))
		end)
	end)
end)
